module.exports = {
	defaultSeverity: "warning",
	extends: ["tslint:recommended"],
	linterOptions: {
		exclude: ["node_modules/**"],
	},
	rules: {
		"jsx-boolean-value": false,
		"jsx-curly-spacing": false,
		"jsx-no-multiline-js": false,
		"jsx-wrap-multiline": false,
		"jsx-alignment": false,
		"jsx-no-lambda": true,
		"jsx-no-string-ref": false,
		"class-name": false,
		"max-line-length": [true, 180],
		"max-classes-per-file": false,
		"member-ordering": [true, "statics-first"],
		"new-parens": true,
		"no-consecutive-blank-lines": true,
		"no-mergeable-namespace": true,
		"no-switch-case-fall-through": true,
		"no-trailing-whitespace": true,
		"no-unused-variable": [true],
		"no-var-keyword": true,
		"one-variable-per-declaration": [false, "ignore-for-loop"],
		"triple-equals": [false, "allow-null-check"],
		"use-isnan": false,

		"prefer-const": false,
		"adjacent-overload-signatures": true,
		"ban-comma-operator": true,
		"ban-type": [true, ["object", "User {} instead."], ["string"]],

		"member-order": [false],
		"no-any": false,
		"no-explicit-any":false,
		"no-empty-interface": true,
		"no-import-side-effect": [
			true,
			{
				"ignore-module": "(\\.html|\\.css)$",
			},
		],
		"no-inferrable-types": [true, "ignore-params", "ignore-properties"],
		"no-internal-module": true,
		"no-magic-numbers": false,
		"no-namespace": false,
		"no-non-null-assertion": true,
		"no-parameter-reassignment": false,
		"no-reference": false,
		"no-unnecessary-type-assertion": true,
		"no-var-requires": true,
		"only-arrow-functions": false,
		"prefer-for-of": true,
		"promise-function-async": true,
		typedef: false,
		"typedef-whitespace": true,
		"unified-signatures": true,
		"await-promise": true,
		curly: true,
		forin: false,
		"import-blacklist": true,
		"label-postion": true,
		"no-arg": true,
		"no-bitwise": false,
		"no-conditional-assignmen": true,
		"no-console": [true, "time", "timeEnd"],
		"no-construct": true,
		"no-debugger": true,
		"no-duplicate-super": true,
		"no-empty": false,
		"no-eval": true,
		"no-floating-promises": true,
		"no-for-in-array": true,
		"no-implicit-dependencies": true,
		"no-inferred-empty-object-type": true,
		"no-invalid-template-strings": true,
		"no-invalid-this": false,
		"no-misused-new": true,
		"no-null-keyword": false,
		"no-object-literal-type-assertion": false,
		"no-return-await": true,
		"arrow-parens": false,
		quotemark: [true, "double", "jsx-double", "avoid-escape"],
		semicolon: false,
		indent: false,
		whitespace: [true, "check-branch", "check-decl", "check-operator", "check-type"],
		"member-access": false,
		"one-line": false,
	},
};
