env:
  browser: false
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-empty-function: off
  "@typescript-eslint/no-explicit-any":
    - off
    - ignoreRestArgs: false
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/ban-types": off
